### ISSUE TITLE
Okay button is unresponsive

### ISSUE THREAD

**Issue by tin2tin** [audacitorch/audacity#66]
**Describe the bug**
Ok button is unresponsive - most of the time(on Win?)

**To Reproduce**
1. On Win, select any filter.
2. Try to click on Okay, it fails

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version Audacity 3.2.0
 - Sound Device: Mime

**Comment by tin2tin** [comment]
Apparently this has to do with the size of the pop-up window?

**Comment by hugofloresgarcia** [comment]
hmm. does it work if you resize the window?

**Comment by tin2tin** [comment]
Yes, it seems to work if the pop up is made full screen.

**Comment by hugofloresgarcia** [comment]
Ah, ok! I'll look into it later this week (probably Friday). I'll have a better idea of a fix then
