### ISSUE TITLE
Dialog for when model fetch fails. 

### ISSUE THREAD

**Issue by aldo-aguilar** [audacitorch/audacity#69]
**Is your feature request related to a problem? Please describe.**
The model manager should not try to fetch models when it has no internet connection

**Describe the solution you'd like**
have the ability to use downloaded models

**Describe alternatives you've considered**
Adding a dialog box to tell the use that there is no internet connection

**Additional context**
Not much other context for this

**Comment by hugofloresgarcia** [comment]
maybe, if the GET request to fetch model cards from the internet fails, we raise a dialog box that says "Error fetching model cards from huggingface"
