### ISSUE TITLE
Better `Add from HuggingFace` error dialogs

### ISSUE THREAD

**Issue by hugofloresgarcia** [audacitorch/audacity#76]
- [] When a user uses `Add from HuggingFace` to add a repo that is meant for the wrong effect, let the user know, and suggest that they should try again in the correct effect. 
- [] When a user tries to use `Add from HuggingFace` to add a repo that is ALREADY in the local set of cards, then let the user know that this card already exists.

**Comment by aldo-aguilar** [comment]
update: this issue does not repro on Windows

**Comment by hugofloresgarcia** [comment]
what's the behavior on windows?
